"""add body stats to user profile

Revision ID: 0b061bb3f9ef
Revises: 55c9f1d75a78
Create Date: 2026-02-22 22:20:19.829277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b061bb3f9ef'
down_revision: Union[str, None] = '55c9f1d75a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profiles', sa.Column('activity_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'activity_level')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'height_cm')
    op.drop_column('user_profiles', 'weight_kg')
    # ### end Alembic commands ###
