"""Add multi-day meal plan model

Revision ID: 55c9f1d75a78
Revises: c4d5e6f7g8h9
Create Date: 2026-02-22 19:19:44.703802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c9f1d75a78'
down_revision: Union[str, None] = 'c4d5e6f7g8h9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_day_meal_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('has_repeats', sa.Boolean(), nullable=False),
    sa.Column('total_unique_meals', sa.Integer(), nullable=False),
    sa.Column('total_repeated_meals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meal_plans', sa.Column('multi_day_plan_id', sa.UUID(), nullable=True))
    op.add_column('meal_plans', sa.Column('day_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal_plans', 'multi_day_meal_plans', ['multi_day_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.drop_column('meal_plans', 'day_number')
    op.drop_column('meal_plans', 'multi_day_plan_id')
    op.drop_table('multi_day_meal_plans')
    # ### end Alembic commands ###
